version: "3.9"

services:
  app:
    container_name: flask_app_greenity
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que se llama así o cámbialo aquí
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=greenity_db

  db:
    container_name: greenity_db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: greenity_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: